# Build settings
title: SSPanel theme
description: SSPanel, SSPanel theme, SSPanel 主题, SSPanel主题, sspanel主题, sspanel.
show_downloads: false
google_analytics:
markdown: kramdown
remote_theme: Czssr/cayman
